### ISSUE TITLE
./makedocker fails

### ISSUE THREAD

**Issue by zahodi** [senorsmile/idris-docker#1]
cabal: Leaving directory '/tmp/cabal-tmp-7/idris-1.3.2'
cabal: Error: some packages failed to install:
idris-1.3.2 failed during the building phase. The exception was:
ExitFailure (-9)
This may be due to an out-of-memory condition.
The command '/bin/sh -c cabal install idris-$IDRIS_VER' returned a non-zero code: 1

**Comment by senorsmile** [comment]
ah, you must not have 32 GB memory.  I think I remember seeing somewhere in idris build docs how to fix that.

**Comment by senorsmile** [comment]
there's a bit at the bottom here: 
https://github.com/idris-lang/Idris-dev/wiki/Idris-on-Ubuntu


Please try latest master.  It should be working as of 
https://github.com/senorsmile/idris-docker/commit/bc6346425db3f3ab286a47f01023eb864e1ace9b

**Comment by senorsmile** [comment]
actually, that had a bug.  master as of https://github.com/senorsmile/idris-docker/commit/7fd617a48a98238699f4f1b2b9495cdeb2d97375 should be working.

**Comment by zahodi** [comment]
still failing:
```
cabal: Leaving directory '/tmp/cabal-tmp-6/idris-1.3.2'
cabal: Error: some packages failed to install:
idris-1.3.2 failed during the building phase. The exception was:
ExitFailure (-9)
This may be due to an out-of-memory condition.
The command '/bin/sh -c cabal install idris-$IDRIS_VER --with-ld=ld.gold' returned a non-zero code: 1
```

I'm running from this commit `b0667f4d6b6a4580bcb45270742eb57761e6ab2f`
cleared off my old images before running the job.

**Comment by senorsmile** [comment]
I tried it on 2 machines and didn't run into any problems.  Could you make sure you're on most recent master commit and try again?

**Comment by zahodi** [comment]
Turns out I need to increase memory on my docker desktop.
